receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  filelog:
    include_file_path: true
    poll_interval: 500ms
    include:
      - /var/tmp/**/*.log

exporters:
  logging:
  datadog:
    hostname: my-host
    api:
      key: $DD_API_KEY

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

extensions:
  trace:
    host: 0.0.0.0
    api:
      key: $DD_API_KEY

service:
  extensions: trace
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [datadog]
    logs:
      receivers: [filelog]
      exporters: [loki]
